client-openai-key={api-key}
client-openai-endpoint=https://ai-proxy.lab.epam.com
client-openai-modelId=gpt-35-turbo-0125

client-openai-modelId.mistral=rlab-mistral-instruct
client-openai-modelId.google=chat-bison@001
client-openai-modelId.amazon=amazon.titan-tg1-large

